name: device
resolution: workspace
description: "Used to get device info"
version: 0.0.1

environment:
  sdk: "^3.12.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: any
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
