name: cineui
resolution: workspace
description: "CineHQ design system"
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.12.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  device:
    path: ../device
  flutter_animate: ^4.5.2
  hugeicons: ^1.1.7
  cached_network_image: ^3.4.1
  go_router: ^17.3.0
  readmore: ^3.0.0
  popover: ^0.4.0
  animated_visibility: ^0.0.4
  custom_tv_text_field: ^1.0.9

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik.ttf
    - family: Teko
      fonts:
        - asset: assets/fonts/Teko.ttf
